FROM ubuntu:24.04
RUN apt update && apt install -y \
    curl \
    git \
    make \
    gcc \
    g++ \
    rpm \
    libudev-dev \
    ripgrep \
    xz-utils \
    libarchive-tools \
    appstream \
    && curl -fsSL https://deb.nodesource.com/setup_24.x | bash - \
    && apt update && apt install -y nodejs \
    && apt -y autoremove \
    && rm -rf /var/lib/apt/lists/*
USER ubuntu
RUN git config --global --add safe.directory '*'
