/*!
 * Copyright (c) 2019 TUXEDO Computers GmbH <tux@tuxedocomputers.com>
 *
 * This file is part of TUXEDO Control Center.
 *
 * TUXEDO Control Center is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * TUXEDO Control Center is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with TUXEDO Control Center.  If not, see <https://www.gnu.org/licenses/>.
 */
export interface ITccFanProfile {
    name: string;
    table: ITccFanTableEntry[];
}

export interface ITccFanTableEntry {
    temp: number;
    speed: number;
}

export const defaultFanProfiles = [
    {
        name: 'Quiet',
        table: [
            { temp: 44, speed: 10 },
            { temp: 45, speed: 10 },
            { temp: 46, speed: 10 },
            { temp: 47, speed: 13 },
            { temp: 48, speed: 13 },
            { temp: 49, speed: 13 },
            { temp: 50, speed: 16 },
            { temp: 51, speed: 16 },
            { temp: 52, speed: 16 },
            { temp: 53, speed: 19 },
            { temp: 54, speed: 19 },
            { temp: 55, speed: 19 },
            { temp: 56, speed: 22 },
            { temp: 57, speed: 22 },
            { temp: 58, speed: 22 },
            { temp: 59, speed: 26 },
            { temp: 60, speed: 26 },
            { temp: 61, speed: 26 },
            { temp: 62, speed: 30 },
            { temp: 63, speed: 30 },
            { temp: 64, speed: 30 },
            { temp: 65, speed: 34 },
            { temp: 66, speed: 35 },
            { temp: 67, speed: 36 },
            { temp: 68, speed: 37 },
            { temp: 69, speed: 41 },
            { temp: 70, speed: 41 },
            { temp: 71, speed: 42 },
            { temp: 72, speed: 43 },
            { temp: 73, speed: 44 },
            { temp: 74, speed: 50 },
            { temp: 75, speed: 50 },
            { temp: 76, speed: 50 },
            { temp: 77, speed: 55 },
            { temp: 78, speed: 55 },
            { temp: 79, speed: 55 },
            { temp: 80, speed: 60 },
            { temp: 81, speed: 60 },
            { temp: 82, speed: 60 },
            { temp: 83, speed: 70 },
            { temp: 84, speed: 70 },
            { temp: 85, speed: 75 },
            { temp: 86, speed: 75 },
            { temp: 87, speed: 80 },
            { temp: 88, speed: 80 },
            { temp: 89, speed: 85 },
            { temp: 90, speed: 85 },
            { temp: 91, speed: 90 },
            { temp: 92, speed: 90 },
            { temp: 93, speed: 95 },
            { temp: 94, speed: 95 },
            { temp: 95, speed: 100 },
            { temp: 96, speed: 100 },
            { temp: 97, speed: 100 },
            { temp: 98, speed: 100 },
            { temp: 99, speed: 100 },
            { temp: 100, speed: 100 }
        ]
    },
    {
        name: 'Balanced',
        table: [
            { temp: 40, speed: 10 },
            { temp: 41, speed: 10 },
            { temp: 42, speed: 12 },
            { temp: 43, speed: 13 },
            { temp: 44, speed: 13 },
            { temp: 45, speed: 15 },
            { temp: 46, speed: 16 },
            { temp: 47, speed: 16 },
            { temp: 48, speed: 18 },
            { temp: 49, speed: 19 },
            { temp: 50, speed: 19 },
            { temp: 51, speed: 22 },
            { temp: 52, speed: 23 },
            { temp: 53, speed: 23 },
            { temp: 54, speed: 26 },
            { temp: 55, speed: 27 },
            { temp: 56, speed: 27 },
            { temp: 57, speed: 30 },
            { temp: 58, speed: 31 },
            { temp: 59, speed: 31 },
            { temp: 60, speed: 32 },
            { temp: 61, speed: 33 },
            { temp: 62, speed: 34 },
            { temp: 63, speed: 37 },
            { temp: 64, speed: 40 },
            { temp: 65, speed: 40 },
            { temp: 66, speed: 43 },
            { temp: 67, speed: 45 },
            { temp: 68, speed: 45 },
            { temp: 69, speed: 47 },
            { temp: 70, speed: 50 },
            { temp: 71, speed: 50 },
            { temp: 72, speed: 53 },
            { temp: 73, speed: 55 },
            { temp: 74, speed: 55 },
            { temp: 75, speed: 57 },
            { temp: 76, speed: 60 },
            { temp: 77, speed: 60 },
            { temp: 78, speed: 65 },
            { temp: 79, speed: 65 },
            { temp: 80, speed: 70 },
            { temp: 81, speed: 70 },
            { temp: 82, speed: 75 },
            { temp: 83, speed: 75 },
            { temp: 84, speed: 80 },
            { temp: 85, speed: 80 },
            { temp: 86, speed: 85 },
            { temp: 87, speed: 85 },
            { temp: 88, speed: 85 },
            { temp: 89, speed: 90 },
            { temp: 90, speed: 90 },
            { temp: 91, speed: 90 },
            { temp: 92, speed: 95 },
            { temp: 93, speed: 95 },
            { temp: 94, speed: 95 },
            { temp: 95, speed: 100 },
            { temp: 96, speed: 100 },
            { temp: 97, speed: 100 },
            { temp: 98, speed: 100 },
            { temp: 99, speed: 100 },
            { temp: 100, speed: 100 }
        ]
    },
    {
        name: 'Cool',
        table: [
            { temp: 40, speed: 15 },
            { temp: 41, speed: 15 },
            { temp: 42, speed: 15 },
            { temp: 43, speed: 15 },
            { temp: 44, speed: 15 },
            { temp: 45, speed: 20 },
            { temp: 46, speed: 20 },
            { temp: 47, speed: 20 },
            { temp: 48, speed: 22 },
            { temp: 49, speed: 25 },
            { temp: 50, speed: 25 },
            { temp: 51, speed: 25 },
            { temp: 52, speed: 25 },
            { temp: 53, speed: 25 },
            { temp: 54, speed: 27 },
            { temp: 55, speed: 30 },
            { temp: 56, speed: 30 },
            { temp: 57, speed: 30 },
            { temp: 58, speed: 32 },
            { temp: 59, speed: 35 },
            { temp: 60, speed: 35 },
            { temp: 61, speed: 37 },
            { temp: 62, speed: 40 },
            { temp: 63, speed: 40 },
            { temp: 64, speed: 42 },
            { temp: 65, speed: 45 },
            { temp: 66, speed: 45 },
            { temp: 67, speed: 45 },
            { temp: 68, speed: 47 },
            { temp: 69, speed: 50 },
            { temp: 70, speed: 50 },
            { temp: 71, speed: 52 },
            { temp: 72, speed: 55 },
            { temp: 73, speed: 55 },
            { temp: 74, speed: 57 },
            { temp: 75, speed: 60 },
            { temp: 76, speed: 60 },
            { temp: 77, speed: 65 },
            { temp: 78, speed: 65 },
            { temp: 79, speed: 70 },
            { temp: 80, speed: 70 },
            { temp: 81, speed: 75 },
            { temp: 82, speed: 75 },
            { temp: 83, speed: 80 },
            { temp: 84, speed: 80 },
            { temp: 85, speed: 85 },
            { temp: 86, speed: 85 },
            { temp: 87, speed: 90 },
            { temp: 88, speed: 90 },
            { temp: 89, speed: 90 },
            { temp: 90, speed: 95 },
            { temp: 91, speed: 95 },
            { temp: 92, speed: 95 },
            { temp: 93, speed: 95 },
            { temp: 94, speed: 95 },
            { temp: 95, speed: 100 },
            { temp: 96, speed: 100 },
            { temp: 97, speed: 100 },
            { temp: 98, speed: 100 },
            { temp: 99, speed: 100 },
            { temp: 100, speed: 100 }
        ]
    }
];
